/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package lab_2_2.webWork.Notebook.src.test.java.Notebook;

import lab_2_2.webWork.Notebook.src.main.java.Notebook.App;
import lab_2_2.webWork.Notebook.src.main.java.Notebook.Notebook;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void appHasAGreeting() {
        App classUnderTest = new App();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }

    @Test void shouldReturnTrueWhenAdditionData(){
        Notebook notebook=new Notebook();
        boolean result=notebook.addition("7.1之前交web作业");
        /**
         * 添加一条记录
         */
        Assertions.assertEquals(true,result);
    }

    @Test void shouldReturnTrueWhenDeleteSingle(){
        Notebook notebook=new Notebook();
        notebook.addition("7.1之前交web作业");
        /**
         * 先添加才能有删除，否则返回false
         */
        boolean result=notebook.deleteSingle(0);
        Assertions.assertEquals(true,result);
    }

    @Test void shouldReturnTrueWhenDeleteAll(){
        Notebook notebook=new Notebook();
        boolean result=notebook.deleteAll();
        Assertions.assertEquals(true,result);
    }
    
    @Test void shouldReturnTrueWhenAccomplish(){
        Notebook notebook=new Notebook();
        notebook.addition("7.1之前交web作业");
        /**
         * 先添加才能修改状态，否则返回false
         */
        boolean result=notebook.accomplish(0);
        Assertions.assertEquals(true,result);
    }
    
    @Test void shouldReturnTrueWhenShowAll(){
        Notebook notebook=new Notebook();
        notebook.addition("7.1之前交web作业");
        notebook.addition("7.17之前买好火车票");
        /**
         * 先添加才能修改状态，否则返回false
         */
        boolean result=notebook.showAll();
        Assertions.assertEquals(true,result);
    }
}
